name: Azure Ai Catalog

on:
  push:
    paths:
      - '.github/workflows/azure-catalog.yml'
      - 'ciScripts/azure-catalog.mts'
      - 'packages/types/src/ai-tools/azure/catalog.ts'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  azure:
    runs-on: ubuntu-24.04-arm
    if: github.actor != 'sushidata-azure[bot]'
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: gh_azure_token
        with:
          app-id: ${{ vars.GH_AZURE_CLIENT_ID }}
          private-key: ${{ secrets.GH_AZURE_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.gh_azure_token.outputs.token }}
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root
      - run: npm  --include-workspace-root run-script install --if-present
      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            packages/*/.tsbuildinfo
            packages/*/dist
          key: tsc-${{ hashFiles('**/*.tsbuildinfo', '**/package-lock.json') }}
          enableCrossOsArchive: true
      - run: npm -w @chainfuse/types run build
      - run: npm run ci:catalog:azure
        env:
          AZURE_SUB_ID: ${{ secrets.AZURE_SUB_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      - name: Git Setup
        run: |
          git config user.name "${{ steps.gh_azure_token.outputs.app-slug }}[bot]"
          git config user.email "${{ vars.GH_AZURE_USER_ID }}+${{ steps.gh_azure_token.outputs.app-slug }}[bot]@users.noreply.github.com"
      - run: git add packages/types/src/ai-tools/azure/catalog.ts
      - run: git commit -m "Updated azure catalog" || echo "catalog not touched"
      - run: git push
