name: Dependabot Changeset
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changeset:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo: true
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.head_ref }}
      - name: Generate changeset file name
        run: |
          SAFE_BRANCH_NAME=$(echo "${{ github.head_ref }}" | sed 's/\//-/g')
          echo "FILENAME=.changeset/$SAFE_BRANCH_NAME.md" >> $GITHUB_OUTPUT
        id: changeset-filename
        shell: bash
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --include-workspace-root
      - name: Get packages affected
        run: |
          npx lerna changed --json | jq -r '.[] | "\"\(.name)\": patch"' | sed '1s/^/---\n/; $s/$/\n---\n/' > ${{ steps.changeset-filename.outputs.FILENAME }}
        shell: bash
      - name: Git Setup
        run: |
          git config user.name "dependabot[bot]"
          git config user.email "dependabot[bot]@users.noreply.github.com"
      - uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
        id: dependabot-metadata
      - name: Extract update type
        run: echo "SEMVER_UPDATE=$(echo "${{ steps.dependabot-metadata.outputs.update-type }}" | cut -d':' -f2)" >> "$GITHUB_OUTPUT"
        id: dependabot-metadata-update-type
      - name: Write changes to changeset
        run: |
          echo "deps(${{ steps.dependabot-metadata-update-type.outputs.SEMVER_UPDATE }}): bump ${{ steps.dependabot-metadata.outputs.dependency-names }}" >> ${{ steps.changeset-filename.outputs.FILENAME }}
        shell: bash
      - run: git add ${{ steps.changeset-filename.outputs.FILENAME }}
      - run: git commit -m "Updated changeset" || echo "Changeset update not needed"
      - run: git push
