name: Cache Nuke

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  delete-cache:
    runs-on: ubuntu-24.04-arm
    permissions: write-all
    steps:
      - uses: step-security/harden-runner@351661ca32ac09a36dc5ee2d536e3128f2a3c8ed # v2.22.0
        with:
          egress-policy: audit
          disable-sudo-and-containers: true
      - run: gh cache delete --all --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}
