name: Build & Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'packages/*/src/**'
      - 'packages/*/__tests__/**'
      - 'package*.json'
      - 'packages/*/package*.json'
      - 'tsconfig.json'
      - 'packages/*/tsconfig*.json'
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/test.yml'
      - 'packages/*/src/**'
      - 'packages/*/__tests__/**'
      - 'package*.json'
      - 'packages/*/package*.json'
      - 'tsconfig.json'
      - 'packages/*/tsconfig*.json'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
          disable-sudo-and-containers: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - run: npm ci --include-workspace-root --workspaces
      - uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            packages/*/.tsbuildinfo
            packages/*/dist
          key: tsc-${{ hashFiles('**/*.tsbuildinfo', '**/package-lock.json') }}
          restore-keys: |
            tsc-
          enableCrossOsArchive: true
      - run: npm run build
      - uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            packages/*/.tsbuildinfo
            packages/*/dist
          key: tsc-${{ hashFiles('**/*.tsbuildinfo', '**/package-lock.json') }}
          enableCrossOsArchive: true
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dist
          path: |
            packages/*/.tsbuildinfo
            packages/*/dist
          compression-level: 9
          # Be nice to github and don't store for long
          retention-days: 1
  test:
    needs: build
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]
        version: ['lts/*', latest]
    continue-on-error: ${{ matrix.os == 'windows-latest' && fromJson('true') || fromJson(inputs.dry_tun_tests || 'false')  }}
    steps:
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-24.04-arm'
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
          disable-sudo-and-containers: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: dist
          path: packages
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.version }}
          check-latest: true
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --include-workspace-root
      - run: npm test -- --since -- --test-reporter=junit --test-reporter-destination=test-output.xml
        env:
          GH_RUNNER_ID: ${{ github.run_id }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CICD_CF_API_TOKEN: ${{ secrets.CICD_CF_API_TOKEN }}
          AI_GATEWAY_API_KEY: ${{ secrets.CICD_CF_API_TOKEN }}
          AZURE_API_KEY_OPENAI_AE_DUBAI: ${{ secrets.AZURE_API_KEY_OPENAI_AE_DUBAI }}
          AZURE_API_KEY_OPENAI_AU_NEWSOUTHWALES: ${{ secrets.AZURE_API_KEY_OPENAI_AU_NEWSOUTHWALES }}
          AZURE_API_KEY_OPENAI_BR_SAOPAULOSTATE: ${{ secrets.AZURE_API_KEY_OPENAI_BR_SAOPAULOSTATE }}
          AZURE_API_KEY_OPENAI_CA_QUEBEC: ${{ secrets.AZURE_API_KEY_OPENAI_CA_QUEBEC }}
          AZURE_API_KEY_OPENAI_CA_TORONTO: ${{ secrets.AZURE_API_KEY_OPENAI_CA_TORONTO }}
          AZURE_API_KEY_OPENAI_CH_GENEVA: ${{ secrets.AZURE_API_KEY_OPENAI_CH_GENEVA }}
          AZURE_API_KEY_OPENAI_CH_ZURICH: ${{ secrets.AZURE_API_KEY_OPENAI_CH_ZURICH }}
          AZURE_API_KEY_OPENAI_EU_FRANKFURT: ${{ secrets.AZURE_API_KEY_OPENAI_EU_FRANKFURT }}
          AZURE_API_KEY_OPENAI_EU_GAVLE: ${{ secrets.AZURE_API_KEY_OPENAI_EU_GAVLE }}
          AZURE_API_KEY_OPENAI_EU_MADRID: ${{ secrets.AZURE_API_KEY_OPENAI_EU_MADRID }}
          AZURE_API_KEY_OPENAI_EU_NETHERLANDS: ${{ secrets.AZURE_API_KEY_OPENAI_EU_NETHERLANDS }}
          AZURE_API_KEY_OPENAI_EU_PARIS: ${{ secrets.AZURE_API_KEY_OPENAI_EU_PARIS }}
          AZURE_API_KEY_OPENAI_EU_WARSAW: ${{ secrets.AZURE_API_KEY_OPENAI_EU_WARSAW }}
          AZURE_API_KEY_OPENAI_IN_CHENNAI: ${{ secrets.AZURE_API_KEY_OPENAI_IN_CHENNAI }}
          AZURE_API_KEY_OPENAI_JP_TOKYO: ${{ secrets.AZURE_API_KEY_OPENAI_JP_TOKYO }}
          AZURE_API_KEY_OPENAI_KR_SEOUL: ${{ secrets.AZURE_API_KEY_OPENAI_KR_SEOUL }}
          AZURE_API_KEY_OPENAI_NO_OSLO: ${{ secrets.AZURE_API_KEY_OPENAI_NO_OSLO }}
          AZURE_API_KEY_OPENAI_SG_SINGAPORE: ${{ secrets.AZURE_API_KEY_OPENAI_SG_SINGAPORE }}
          AZURE_API_KEY_OPENAI_UK_LONDON: ${{ secrets.AZURE_API_KEY_OPENAI_UK_LONDON }}
          AZURE_API_KEY_OPENAI_US_CALIFORNIA: ${{ secrets.AZURE_API_KEY_OPENAI_US_CALIFORNIA }}
          AZURE_API_KEY_OPENAI_US_ILLINOIS: ${{ secrets.AZURE_API_KEY_OPENAI_US_ILLINOIS }}
          AZURE_API_KEY_OPENAI_US_PHOENIX: ${{ secrets.AZURE_API_KEY_OPENAI_US_PHOENIX }}
          AZURE_API_KEY_OPENAI_US_TEXAS: ${{ secrets.AZURE_API_KEY_OPENAI_US_TEXAS }}
          AZURE_API_KEY_OPENAI_US_VIRGINIA: ${{ secrets.AZURE_API_KEY_OPENAI_US_VIRGINIA }}
          AZURE_API_KEY_OPENAI_US_VIRGINIA2: ${{ secrets.AZURE_API_KEY_OPENAI_US_VIRGINIA2 }}
          AZURE_API_KEY_OPENAI_ZA_JOHANNESBURG: ${{ secrets.AZURE_API_KEY_OPENAI_ZA_JOHANNESBURG }}
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
          WORKERS_AI_API_KEY: ${{ secrets.CICD_CF_API_TOKEN }}
      - uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        if: always()
        with:
          paths: packages/*/test-output.xml
          show: all
