name: Workers Ai Catalog

on:
  push:
    paths:
      - '.github/workflows/workers-ai-catalog.yml'
      - 'packages/types/src/ai-tools/workers-ai/catalog.ts'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  workersAi:
    runs-on: ubuntu-24.04-arm
    if: github.actor != 'sushidata-cloudflare[bot]'
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo-and-containers: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: gh_cloudflare_token
        with:
          app-id: ${{ vars.GH_CLOUDFLARE_CLIENT_ID }}
          private-key: ${{ secrets.GH_CLOUDFLARE_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ steps.gh_cloudflare_token.outputs.token }}
      - name: Git Setup
        run: |
          git config user.name "${{ steps.gh_cloudflare_token.outputs.app-slug }}[bot]"
          git config user.email "${{ vars.GH_CLOUDFLARE_USER_ID }}+${{ steps.gh_cloudflare_token.outputs.app-slug }}[bot]@users.noreply.github.com"
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            await Promise.all([
                fetch(new URL(`client/v4/accounts/${process.env.CF_ACCOUNT_ID}/ai/models/search`, 'https://api.cloudflare.com'), {
                    headers: {
                        Authorization: `Bearer ${process.env.CICD_CF_API_TOKEN}`,
                    },
                }).then((modelResponse) => {
                    if (modelResponse.ok) {
                        return modelResponse.json();
                    } else {
                        throw new Error(modelResponse.statusText, { cause: modelResponse.status });
                    }
                }),
                fetch(new URL(`client/v4/accounts/${process.env.CF_ACCOUNT_ID}/ai/finetunes`, 'https://api.cloudflare.com'), {
                    headers: {
                        Authorization: `Bearer ${process.env.CICD_CF_API_TOKEN}`,
                    },
                }).then((privateLoraResult) => {
                    if (privateLoraResult.ok) {
                        return privateLoraResult.json();
                    } else {
                        throw new Error(privateLoraResult.statusText, { cause: privateLoraResult.status });
                    }
                }),
                fetch(new URL(`client/v4/accounts/${process.env.CF_ACCOUNT_ID}/ai/finetunes/public`, 'https://api.cloudflare.com'), {
                    headers: {
                        Authorization: `Bearer ${process.env.CICD_CF_API_TOKEN}`,
                    },
                }).then((publicLoraResult) => {
                    if (publicLoraResult.ok) {
                        return publicLoraResult.json();
                    } else {
                        throw new Error(publicLoraResult.statusText, { cause: publicLoraResult.status });
                    }
                }),
            ]).then(async ([{ result: modelJson }, { result: privateLoraJson }, { result: publicLoraJson }]) => {
                const grouped = {};

                modelJson.forEach((model) => {
                    // Pull out model group into a upper level key
                    const taskName = model.task.name;
                    if (!grouped[taskName]) {
                        grouped[taskName] = {
                            id: model.task.id,
                            description: model.task.description,
                            models: [],
                        };
                    }

                    const { task, ...modelWithoutTask } = model;

                    // Convert stringified values to primitives, if possible
                    const properties = model.properties.reduce((acc, prop) => {
                        let value = prop.value;
                        if (['true', 'false', '0', '1', 0, 1].includes(value)) {
                            value = Boolean(value);
                        } else if (!isNaN(value)) {
                            value = Number(value);
                        }
                        acc[prop.property_id] = value;
                        return acc;
                    }, {});

                    grouped[taskName].models.push({ ...modelWithoutTask, properties });
                });

                await import('node:fs').then(({ createWriteStream }) => {
                    const writeStream = createWriteStream('packages/types/src/ai-tools/workers-ai/catalog.ts', { encoding: 'utf8' });
                    writeStream.write(
                        `export const workersAiCatalog = ${JSON.stringify(
                            {
                                modelGroups: grouped,
                                loras: [...privateLoraJson, ...publicLoraJson].map((lora) => ({
                                    // The api endpoint doesn't provide `public` on the private endpoint
                                    public: false,
                                    // Convert stringified values to primitives, if possible
                                    ...Object.entries(lora).reduce((acc, prop) => {
                                        console.log('prop', prop);
                                        let value = prop[1];
                                        if (['true', 'false', '0', '1', 0, 1].includes(value)) {
                                            value = Boolean(value);
                                        } else if (!isNaN(value)) {
                                            value = Number(value);
                                        }
                                        acc[prop[0]] = value;
                                        return acc;
                                    }, {}),
                                })),
                            },
                            null,
                            '\t',
                        )} as const`,
                    );
                    writeStream.end();
                });
            });
        env:
          CICD_CF_API_TOKEN: ${{ secrets.CICD_CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root
      - run: npm  --include-workspace-root run-script install --if-present
      - run: npx prettier --write packages/types/src/ai-tools/workers-ai/catalog.ts
      - run: git add packages/types/src/ai-tools/workers-ai/catalog.ts
      - run: git commit -m "Updated workers-ai model catalog" || echo "model catalog not touched"
      - run: git push
