name: Workers Ai Catalog

on:
  push:
    paths:
      - '.github/workflows/workers-ai-catalog.yml'
      - 'packages/types/src/ai-tools/workers-ai/catalog.ts'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workersAi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await Promise.all([
                fetch(new URL(`client/v4/accounts/${process.env.CF_ACCOUNT_ID}/ai/models/search`, 'https://api.cloudflare.com'), {
                    headers: {
                        Authorization: `Bearer ${process.env.CICD_CF_API_TOKEN}`,
                    },
                }).then((modelResponse) => {
                    if (modelResponse.ok) {
                        return modelResponse.json();
                    } else {
                        throw new Error(modelResponse.statusText, { cause: modelResponse.status });
                    }
                }),
                fetch(new URL(`client/v4/accounts/${process.env.CF_ACCOUNT_ID}/ai/finetunes`, 'https://api.cloudflare.com'), {
                    headers: {
                        Authorization: `Bearer ${process.env.CICD_CF_API_TOKEN}`,
                    },
                }).then((privateLoraResult) => {
                    if (privateLoraResult.ok) {
                        return privateLoraResult.json();
                    } else {
                        throw new Error(privateLoraResult.statusText, { cause: privateLoraResult.status });
                    }
                }),
                fetch(new URL(`client/v4/accounts/${process.env.CF_ACCOUNT_ID}/ai/finetunes/public`, 'https://api.cloudflare.com'), {
                    headers: {
                        Authorization: `Bearer ${process.env.CICD_CF_API_TOKEN}`,
                    },
                }).then((publicLoraResult) => {
                    if (publicLoraResult.ok) {
                        return publicLoraResult.json();
                    } else {
                        throw new Error(publicLoraResult.statusText, { cause: publicLoraResult.status });
                    }
                }),
            ]).then(async ([{ result: modelJson }, { result: privateLoraJson }, { result: publicLoraJson }]) => {
                const grouped = {};

                modelJson.forEach((model) => {
                    // Pull out model group into a upper level key
                    const taskName = model.task.name;
                    if (!grouped[taskName]) {
                        grouped[taskName] = {
                            id: model.task.id,
                            description: model.task.description,
                            models: [],
                        };
                    }

                    const { task, ...modelWithoutTask } = model;

                    // Convert stringified values to primitives, if possible
                    const properties = model.properties.reduce((acc, prop) => {
                        let value = prop.value;
                        if (['true', 'false', '0', '1', 0, 1].includes(value)) {
                            value = Boolean(value);
                        } else if (!isNaN(value)) {
                            value = Number(value);
                        }
                        acc[prop.property_id] = value;
                        return acc;
                    }, {});

                    grouped[taskName].models.push({ ...modelWithoutTask, properties });
                });

                await import('node:fs').then(({ createWriteStream }) => {
                    const writeStream = createWriteStream('packages/types/src/ai-tools/workers-ai/catalog.ts', { encoding: 'utf8' });
                    writeStream.write(
                        `export const workersAiCatalog = ${JSON.stringify(
                            {
                                modelGroups: grouped,
                                loras: [...privateLoraJson, ...publicLoraJson].map((lora) => ({
                                    // The api endpoint doesn't provide `public` on the private endpoint
                                    public: false,
                                    // Convert stringified values to primitives, if possible
                                    ...Object.entries(lora).reduce((acc, prop) => {
                                        console.log('prop', prop);
                                        let value = prop[1];
                                        if (['true', 'false', '0', '1', 0, 1].includes(value)) {
                                            value = Boolean(value);
                                        } else if (!isNaN(value)) {
                                            value = Number(value);
                                        }
                                        acc[prop[0]] = value;
                                        return acc;
                                    }, {}),
                                })),
                            },
                            null,
                            '\t',
                        )} as const`,
                    );
                    writeStream.end();
                });
            });
        env:
          CICD_CF_API_TOKEN: ${{ secrets.CICD_CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --include-workspace-root
      - run: npx prettier --write packages/types/src/ai-tools/workers-ai/catalog.ts
      - name: Git Setup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: git add packages/types/src/ai-tools/workers-ai/catalog.ts
      - run: git commit -m "Updated workers-ai model catalog" || echo "model catalog not touched"
      - run: git push
